### ISSUE TITLE
'Chrome has stopped'

### ISSUE THREAD

**Issue by PinhaEsquilo** [nikolajakshic/instagramauth#2]
Why i getting the error 'Chrome has stopped'?
When i run your project works perfectly but when i implementing on my project EVERY TIME chrome crashes.

my Logcat says:

`    --------- beginning of crash
2018-09-25 04:29:05.744 7582-7582/com.android.chrome:sandboxed_process0 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.chrome:sandboxed_process0, PID: 7582
    android.content.res.Resources$NotFoundException: Array resource ID #0x7f030009
        at android.content.res.Resources.obtainTypedArray(Resources.java:618)
        at android.content.res.Resources.preloadFonts(Resources.java:380)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5769)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.WebViewZygoteInit.main(WebViewZygoteInit.java:146)`

**Comment by PinhaEsquilo** [comment]
@nikolajakshic When I create a new app. seems fine!. but when I try to use on my app. the 'Chrome' crash and says 'Chrome has stopped' `W/cr_CrashFileManager: /data/user/0/com.example.example.nanoDigital/cache/WebView/Crash Reports does not exist or is not a directory` please look at this video! i recorded to show the error [https://www.youtube.com/watch?v=taf0joTMLW0](url)

**Comment by nikolajakshic** [comment]
`W/cr_CrashFileManager: /data/user/0/com.example.example.nanoDigital/cache/WebView/Crash Reports does not exist or is not a directory` - This is just a warning, nothing to worry about.

Can you reproduce the bug on a small sample project and send it to me, so I can try to debug it?

**Comment by PinhaEsquilo** [comment]
@nikolajakshic I found the problem LOOL! it was my strings.xml LOL. if i remove all my usage string in xml and leave only the `<string name="user_id">ID: %1$s</string>
    <string name="user_name">Name: %1$s</string>
    <string name="user_full_name">Full name: %1$s</string>` the api works perfectly LOL but i really need to use these strings in xml! if you need to debug just download my sample and try by yourself = http://www.mediafire.com/file/9hlnm10dw84t870/SollerDigital.rar  **I modified the logo because you know... business =D** **DOWNLOAD THE SAMPLE AND RUN ON DEVICE PIXEL 2XL AND CLICK ON BUTTON 'INFLUENCER' BECAUSE I NOT COMPLETE THE BRAND PART xP. YOU WILL SEE THE ERROR 'Chrome has stopped...** **GO TO STRINGS.XML AND DELETE ALL STRING BUT LEAVE ONLY THOSE** `<string name="user_id">ID: %1$s</string>
    <string name="user_name">Name: %1$s</string>
    <string name="user_full_name">Full name: %1$s</string>` I really want your api project on my app :( I hope you have another solution, i hope you like the visual layout =D.

**Comment by PinhaEsquilo** [comment]
Google drive = https://drive.google.com/file/d/1cQVH2BYXbQDmoKbOZFuFBNLvyENFuv0j/view

**Comment by nikolajakshic** [comment]
There was a build error, in some layouts you used @color/white, in others @color/**W**hite (with capital W). Once I fixed that, application worked fine. Tried on multiple emulators and one physical device, couldn't reproduce the bug.

**Comment by PinhaEsquilo** [comment]
@nikolajakshic LOL sorry about the build error!. try this sample now! = https://drive.google.com/file/d/1xJFgG4PI2Tq0bnLmmlz1DmqztToqWnli/view = https://www.mediafire.com/file/lp5apz3cezr7ffb/SollerDigital.rar/file **They will give you the message 'Chrome has stopped' then go to strings.xml and delete all thoese strings and leave only the** ` <string name="user_id">ID: %1$s</string>
    <string name="user_name">Name: %1$s</string>
    <string name="user_full_name">Full name: %1$s</string>` I don't know if this is a bug. but i really need all those strings. i hope you help me. **I RECOMMEND OPENING WITH PIXEL 2 XL**

**Comment by PinhaEsquilo** [comment]
@nikolajakshic I recorded the problem and the solution =D = https://www.youtube.com/watch?v=CVQUs_JThng **My pc was sh*t sorry about that :'(**

**Comment by PinhaEsquilo** [comment]
@nikolajakshic I found the problem LOL it was my <string-array> month and year!. i use those <string-array> for my 'spinner' 
![problem](https://user-images.githubusercontent.com/25893893/46189364-ac9aba00-c2c4-11e8-8484-b0c88f427d48.png)

**Comment by PinhaEsquilo** [comment]
@nikolajakshic I can get how much followers people has?. = https://www.instagram.com/developer/changelog/

**Comment by nikolajakshic** [comment]
There is a reported [issue](https://issuetracker.google.com/u/0/issues/65575496) with Android System WebView when using preloaded fonts. We need to wait for the Android Team to fix that.

Temporary workaround is to remove preloaded fonts from the manifest file:

```xml
<meta-data
    android:name="preloaded_fonts"
    android:resource="@array/preloaded_fonts" />
```
