### ISSUE TITLE
Use info multiple times.

### ISSUE THREAD

**Issue by PinhaEsquilo** [nikolajakshic/instagramauth#5]
How can i use userinfo more than once? like photo, fullname?.
I going to use the infos in my 'drawerlayout' like this photo

I tired to use the same id but the image and the name not load.
And i tired to create a new (ImageView) and (TextView) but i getting error

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.non.phas, PID: 6427
    java.lang.NullPointerException: Argument must not be null
        at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:31)
        at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:25)
        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:675)
        at com.example.non.phas.DIPerfil$2.onSuccess(DIPerfil.java:97)
        at com.example.non.phas.DIPerfil$2.onSuccess(DIPerfil.java:93)
        at com.nikola.jakshic.instagramauth.AuthManager$getUserInfoAsync$1.onSuccess(AuthManager.kt:112)
        at com.nikola.jakshic.instagramauth.AuthManager$getUserInfoAsync$1.onSuccess(AuthManager.kt:110)`

**Comment by PinhaEsquilo** [comment]
Error When i create a new ID

`    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.fqrgotten.sollerdigital, PID: 6427
    java.lang.NullPointerException: Argument must not be null
        at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:31)
        at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:25)
        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:675)
        at com.example.fqrgotten.sollerdigital.DIPerfil$2.onSuccess(DIPerfil.java:97)
        at com.example.fqrgotten.sollerdigital.DIPerfil$2.onSuccess(DIPerfil.java:93)
        at com.nikola.jakshic.instagramauth.AuthManager$getUserInfoAsync$1.onSuccess(AuthManager.kt:112)
        at com.nikola.jakshic.instagramauth.AuthManager$getUserInfoAsync$1.onSuccess(AuthManager.kt:110)
        at com.nikola.jakshic.instagramauth.InstagramServiceImpl$getUserInfoAsync$1$1.run(InstagramServiceImpl.kt:68)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

![outro](https://user-images.githubusercontent.com/25893893/46338940-ea227e80-c607-11e8-8879-6af47b9314ae.png)

**Comment by nikolajakshic** [comment]
This is not the issue with the library. Your `DIMenuDrawerFoto` variable is `null` because you need to inflate the header view first, as it is not inflated automatically.
```java
View header = navigationView.getHeaderView(0);
DIMenuDrawerFoto = header.findViewById(R.id.DIMenuDrawerFoto);
```
